Repository SeungHyunLee054/Ticket-911-spring, pull requests merged in 2025-05, with the labels that each got.

#8 Feature: 로그아웃 기능추가, 테스트 코드
  src/main/java/nbc/ticketing/ticket911/application/auth/service/AuthService.java
  src/main/java/nbc/ticketing/ticket911/domain/auth/controller/AuthController.java
  src/main/java/nbc/ticketing/ticket911/infrastructure/gitkeep
  src/test/java/nbc/ticketing/ticket911/application/auth/service/AuthServiceTest.java
Labels: enhancement

#10 Feat: 유저 기능, 테스트
  src/main/java/nbc/ticketing/ticket911/application/user/service/UserService.java
  src/main/java/nbc/ticketing/ticket911/domain/user/controller/UserController.java
  src/main/java/nbc/ticketing/ticket911/domain/user/dto/request/UpdateUserRequestDto.java
  src/main/java/nbc/ticketing/ticket911/domain/user/entity/User.java
  src/main/java/nbc/ticketing/ticket911/domain/user/service/UserDomainService.java
  src/main/java/nbc/ticketing/ticket911/infrastructure/security/jwt/constant/JwtConstants.java
  src/test/java/nbc/ticketing/ticket911/application/user/service/UserServiceTest.java
  src/test/java/nbc/ticketing/ticket911/domain/user/controller/UserControllerTest.java
  src/test/java/nbc/ticketing/ticket911/domain/user/service/UserDomainServiceTest.java
  src/test/java/nbc/ticketing/ticket911/support/security/TestSecurityConfig.java
  src/test/java/nbc/ticketing/ticket911/support/security/WithCustomMockUser.java
  src/test/java/nbc/ticketing/ticket911/support/security/WithCustomMockUserSecurityContextFactory.java
Labels: enhancement

#18 Refector : concert & concetSeat
  src/main/java/nbc/ticketing/ticket911/application/concert/service/ConcertService.java
  src/main/java/nbc/ticketing/ticket911/application/concertseat/service/ConcertSeatService.java
  src/main/java/nbc/ticketing/ticket911/domain/concert/application/service/ConcertService.java
  src/main/java/nbc/ticketing/ticket911/domain/concert/controller/ConcertController.java
  src/main/java/nbc/ticketing/ticket911/domain/concert/exception/code/ConcertExceptionCode.java
  src/main/java/nbc/ticketing/ticket911/domain/concert/repository/ConcertQueryRepositoryImpl.java
  src/main/java/nbc/ticketing/ticket911/domain/concert/repository/ConcertRepository.java
  src/main/java/nbc/ticketing/ticket911/domain/concert/service/ConcertDomainService.java
  src/main/java/nbc/ticketing/ticket911/domain/concertseat/application/service/ConcertSeatService.java
  src/main/java/nbc/ticketing/ticket911/domain/concertseat/controller/ConcertSeatController.java
  src/main/java/nbc/ticketing/ticket911/domain/concertseat/entity/ConcertSeat.java
  src/main/java/nbc/ticketing/ticket911/domain/concertseat/service/ConcertSeatDomainService.java
  src/test/java/nbc/ticketing/ticket911/application/concert/service/ConcertServiceTest.java
Labels: refactor

#25 Feture : Lettuce
  build.gradle
  src/main/java/nbc/ticketing/ticket911/common/annotation/RedissonMultiLock.java
  src/main/java/nbc/ticketing/ticket911/common/lock/lettuce/DistributedLockService.java
  src/main/java/nbc/ticketing/ticket911/common/lock/lettuce/LettuceConfig.java
  src/main/java/nbc/ticketing/ticket911/common/lock/lettuce/LettuceDistributedLockService.java
  src/main/java/nbc/ticketing/ticket911/common/lock/lettuce/LettuceLockAspect.java
  src/main/java/nbc/ticketing/ticket911/common/lock/lettuce/LettuceLockManager.java
  src/main/java/nbc/ticketing/ticket911/common/lock/lettuce/LettuceMultiLock.java
  src/main/java/nbc/ticketing/ticket911/config/LettuceConfig.java
  src/main/java/nbc/ticketing/ticket911/domain/auth/vo/AuthUser.java
  src/main/java/nbc/ticketing/ticket911/domain/booking/application/BookingFacade.java
  src/main/java/nbc/ticketing/ticket911/domain/booking/application/BookingService.java
  src/main/java/nbc/ticketing/ticket911/domain/booking/controller/BookingController.java
  src/main/java/nbc/ticketing/ticket911/domain/booking/exception/code/BookingExceptionCode.java
  src/main/java/nbc/ticketing/ticket911/domain/user/service/UserDomainService.java
  src/test/java/nbc/ticketing/ticket911/application/concert/service/ConcertServiceTest.java
  src/test/java/nbc/ticketing/ticket911/domain/booking/application/BookingServiceTest.java
  src/test/java/nbc/ticketing/ticket911/domain/concert/application/LettuceLockTest.java
Labels: enhancement

#30 Docs: README 추가
  README.md
Labels: documentation
